### ISSUE TITLE
Open template file in {include macro

### ISSUE THREAD

**Issue by chemix** [nette-intellij/intellij-latte#103]
`ctrl+B` - (win) go to declaration, 

when the cursor is in the file name, that will be nice for "go to declaration" open the file ? :-)

is it posssible this behaviour implemented? 

![image](https://user-images.githubusercontent.com/42802/87223493-ce700e80-c37d-11ea-99a5-f27b966526d7.png)

**Comment by mesour** [comment]
@chemix: I tried to implement this in the past, but without success. I couldn't mark it as a specific token at the Lexer level.

If more time was spent on it, I think it would be possible.

**Comment by solcik** [comment]
@mesour there may be some insight taken from this plugin?  https://github.com/Haehnchen/idea-php-laravel-plugin

**Comment by mesour** [comment]
@solcik Thanks, I'll look into it as I work on it, maybe it will be useful.

**Comment by mesour** [comment]
Can be realised with https://github.com/nette-intellij/intellij-latte/issues/160

**Comment by mesour** [comment]
Possible solution?

EP: `com.intellij.include.provider`

[FileIncludeProvider](https://upsource.jetbrains.com/idea-ce/file/idea-ce-f3337ede11680b745f513943772150ee781a51c0/platform/lang-impl/src/com/intellij/psi/impl/include/FileIncludeProvider.java?_ga=2.105878659.1470719218.1634858572-850508708.1619467312) provides information about include statements resolving to files (e.g., `<xi:include>` in XML). Including/included files can then be obtained via [FileIncludeManager](https://upsource.jetbrains.com/idea-ce/file/idea-ce-f3337ede11680b745f513943772150ee781a51c0/platform/lang-api/src/com/intellij/psi/impl/include/FileIncludeManager.java?_ga=2.13998007.1470719218.1634858572-850508708.1619467312).

**Comment by mesour** [comment]
Implemented in Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro
