### ISSUE TITLE
Fix variables detection, inspections etc.

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#104]
- [x] Used variables defined in `{define}` tag (issue: https://github.com/nette-intellij/intellij-latte/issues/84)
- [x] Contexts for variables
- [x] Multiple variable definitions: https://github.com/nette-intellij/intellij-latte/issues/124
- [x] Maybe use another PSI reference for variable definitions

**Comment by SendiMyrkr** [comment]
Is part of this multiple definition with more ```{define}``` tags in one file?

![define-multiple](https://user-images.githubusercontent.com/1462122/97213733-4d207880-17c2-11eb-9a04-8c34011b11ca.png)

**Comment by mesour** [comment]
@SendiMyrkr for now yes, thank you for report

**Comment by mesour** [comment]
@SendiMyrkr i moved it to https://github.com/nette-intellij/intellij-latte/issues/84

**Comment by mesour** [comment]
1.1.3 is released. In 1-2 business days will be available for download from plugins.jetbrains.com.
