### ISSUE TITLE
Nested blocks are triggering error

### ISSUE THREAD

**Issue by sasule** [nette-intellij/intellij-latte#109]
When nesting blocks error is triggered. 
![image](https://user-images.githubusercontent.com/2640351/87659045-46af4900-c75d-11ea-8adc-2d7841914faa.png)

Block of code is taken from latte documentation (https://latte.nette.org/en/tags#toc-blocks) so it should be OK.

The real world piece of code (sorry for fomatting):
`{block h1}
    <div n:tag-if="$mastersManageAllowed" class="d-flex w-100 justify-content-between">
        <h1 n:block="foo" class="section-h1">ITF Masters</h1>
        <div n:if="$mastersManageAllowed" class="buttons">
            <a n:href="openMasterForm!" data-modal-open="masterModal" class="btn btn-itf-filter edit-modal">
                <i class="fas fa-plus-square mr-2 "></i>
                Add a master
            </a>
        </div>
    </div>
{/block}`

The error is: <outer html>, LatteTokenType.T_HTML_TAG_NATTR_NAME, LatteTokenType.T_MACRO_COMMENT or LatteTokenType.T_MACRO_OPEN_TAG_OPEN expected, got '{/'

**Comment by mesour** [comment]
@sasule Thank you for reporting. This problem is with `block`, `_` and `label` tags. I will try to fix it as soon as possible.

**Comment by mesour** [comment]
Fixed in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)
