### ISSUE TITLE
Different behavior when double-click on variable inside include macro.

### ISSUE THREAD

**Issue by sasule** [nette-intellij/intellij-latte#111]
When double-click is performed  inside double quotes, only one letter is selected.

```
 {include Gmodal,
    modalId => "provisionInvoiceFormModal",
    modalLabel => "provisionInvoiceFormModalLabel",
    modalTitle => "Faktura v PDF",
    ...
    }
```

When double-clicked inside single quotes then is selected whole string, e.g. "generateProvisionsFormModal"
```
    {include Gmodal,
    modalId => 'generateProvisionsFormModal',
    modalLabel => 'generateProvisionsFormModalLabel',
   ...
    }
```
Expected behaviour - single or double qouted content is double-clicked, so whole string inside quotes should be selected.

**Comment by mesour** [comment]
Fixed in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)
