### ISSUE TITLE
Error using block macro with a translate macro within

### ISSUE THREAD

**Issue by medhi** [nette-intellij/intellij-latte#116]
Example of code, which generates the error:

`{block description}{_front.domains.desc}{/block}`

Error: 

<outer html>, LatteTokenType.T_HTML_TAG_NATTR_NAME, LatteTokenType.T_MACRO_COMMENT or LatteTokenType.T_MACRO_OPEN_TAG_OPEN expected, got '{/'

**Comment by sasule** [comment]
Quick and dirty temporary solution:
```{block description}{("front.domains.desc")|translate}{/block}```

Maybe it's related with #109

**Comment by mesour** [comment]
Fixed in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)
