### ISSUE TITLE
Support n:macro and unpaired {macro}

### ISSUE THREAD

**Issue by pepa-linha** [nette-intellij/intellij-latte#120]
Add support for unpaired `{macro}` and `n: macro`, please.

Temporary resolved by this tag
`<tag name="asset" type="AUTO_EMPTY" arguments="source" />`

but it also adds unexpected `n:tag-macro` and so on...

Thanks.

**Comment by mesour** [comment]
Fixed in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)
