### ISSUE TITLE
Incorrect "Multiple definitions for variable" when used in foreach in block

### ISSUE THREAD

**Issue by josefsabl** [nette-intellij/intellij-latte#124]
This code ...

```latte
{var $foos = []}
<div n:foreach="$foos as $foo"></div>
```

... is marked as erroneous when put into block.

```latte
{define bar}
    {var $foos = []}
    <div n:foreach="$foos as $foo"></div>
{/define}
```

![2020-10-19_10h30_05](https://user-images.githubusercontent.com/1252386/96420664-0fd24e80-11f6-11eb-8551-fcdf99be720b.png)

**Comment by mesour** [comment]
Next problem from @solcik:

I have to redeclare the variable inside the `snippet` tag. So I think it should not make a warning for multiple definitions.

```latte
    {var $T = 'app.translator.namespace'}
    {* .... *}
    <div n:snippet="videos">
        {var $T = 'app.translator.namespace'}
    </div>
    {* .... *}
```

<img width="345" alt="Screenshot 2020-11-21 at 12 42 08" src="https://user-images.githubusercontent.com/1543737/99876443-0bcf8d00-2bf7-11eb-8a0e-ff6a5545a0ed.png">

**Comment by mesour** [comment]
Info from @SendiMyrkr:

Is part of this multiple definition with more {define} tags in one file?

![97213733-4d207880-17c2-11eb-9a04-8c34011b11ca](https://user-images.githubusercontent.com/1161897/117559752-4c797080-b088-11eb-8bff-a746b5a2c0e9.png)

**Comment by mesour** [comment]
solved in 1.1.3-RC1 - How to install EAP - https://github.com/nette-intellij/intellij-latte#testing-eap-versions

**Comment by SendiMyrkr** [comment]
My example si correct now.

**Comment by mesour** [comment]
1.1.3 is released. In 1-2 business days will be available for download from plugins.jetbrains.com.
