### ISSUE TITLE
Condition and translation tags combination breaks the indentation

### ISSUE THREAD

**Issue by jaroslavlibal** [nette-intellij/intellij-latte#125]
I've been using the `{_'foo.bar '}` latte tags for translations for a long time. However when I use the current (1.1.1-RC1) version of your plugin, then it behaves strangely in combination with the condition.

If I don't use the paired variant for the last translation of the template and I use reformat function, then it breaks the indentation.

Example result:
```latte
{if $foo} {* wrong *}
    <div>
    {_'dsd'}
    </div>
{/if}
{if $foo} {* correct *}
    <div>
        {_}dsd{/_}
    </div>
{/if}
{if $foo} {* correct *}
    <div>
        {_'dsd'}
    </div>
    <div>
        {_}dsd{/_}
    </div>
{/if}
{if $foo} {* wrong *}
    <div>
        {_'dsd'}
    </div>
    <div>
        {_}dsd{/_}
    </div>
    <div>
    {_'dsd'}
    </div>
{/if}
```

**Comment by mesour** [comment]
Fixed in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)
