### ISSUE TITLE
Multiple definions inside snippet tag

### ISSUE THREAD

**Issue by solcik** [nette-intellij/intellij-latte#132]
I have to redeclare the variable inside the `snippet` tag. So I think it should not make a warning for multiple definitions.

```latte
    {var $T = 'app.translator.namespace'}
    {* .... *}
    <div n:snippet="videos">
        {var $T = 'app.translator.namespace'}
    </div>
    {* .... *}
```

<img width="345" alt="Screenshot 2020-11-21 at 12 42 08" src="https://user-images.githubusercontent.com/1543737/99876443-0bcf8d00-2bf7-11eb-8a0e-ff6a5545a0ed.png">

**Comment by mesour** [comment]
This is duplication for https://github.com/nette-intellij/intellij-latte/issues/124#issuecomment-835656306. I moved your commend to the master issue and close this issue.
