### ISSUE TITLE
Latte plugin 1.1.0 errors - PHPStorm 2020.3

### ISSUE THREAD

**Issue by kropacekt** [nette-intellij/intellij-latte#134]
Hey,

Latte plugin have some problems on new PHPStorm version which was recently released.

There is (for example) problem with autocompleting classes. 

Reports:
[stacktrace.txt](https://github.com/nette-intellij/intellij-latte/files/5641124/stacktrace.txt)
[induced.txt](https://github.com/nette-intellij/intellij-latte/files/5641127/induced.txt)

**Comment by mesour** [comment]
@kropacekt and which version of the plugin are you using?

**Comment by mesour** [comment]
@kropacekt try 1.1.1-RC2, install it by following this manual: https://github.com/nette-intellij/intellij-latte#testing-eap-versions

**Comment by kropacekt** [comment]
Yeah, after installing 1.1.1-RC2 is everything alright, thanks :)
