### ISSUE TITLE
PhpStorm 2020.3: add custom pair tag is not saved

### ISSUE THREAD

**Issue by Lumeriol** [nette-intellij/intellij-latte#136]
If I have any unknown tag like "multiplier" and want to add to custom tags via Alt+Enter or manually in Settings, it seems that it is added, but with first automatic save of PhpStorm (or with Ctrl+S) Balloon popup / Event log is shown with message "Unable to save settings: Failed to save settings. Please restart PhpStorm".
After restart application custom tag is not saved - in Settings of Latte there is empty list.

Tested with Latte 1.1.1-RC2

With PHPStorm 2020.2.4 there is not this problem, reparsing Latte files has no effect.

**Comment by mesour** [comment]
@Lumeriol try [xml-configuration-files (documentation)](https://github.com/nette-intellij/intellij-latte/blob/master/docs/en/xmlFilesConfiguration.md#xml-configuration-files) instead of adding new Latte tags in settings.

**Comment by mesour** [comment]
From duplicated issues:

@savalo:
> Same problem with saving custom latte tags in 1.1.1-RC2:
> Unable to save settings: Failed to save settings. Please restart PhpStorm
> Pstorm is trying to repeat save custom tags repeatedly..

@NoxArt
> Hi, since PhpStorm 2020.3 whenever I change something (e.g. register a macro) and save, I get a message "Failed to save settings. Please restart PhpStorm", but there is no callstack or more info. After restart macro will not be registered
Version is 1.1.1-RC2, but the same issue was iirc with 1.1.0 and 1.0.2 on this PHPStorm version (I've been trying to solve #138 so I tried older versions)
Let me know if I should provide more info or try something
Thank you!

**Comment by mesour** [comment]
It is fixed in [v1.1.2-RC1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.2-RC1) will soon be available in [the EAP channel](https://github.com/nette-intellij/intellij-latte#testing-eap-versions) from the JetBrains repository.
