### ISSUE TITLE
Reformating code adds an empty row under comments

### ISSUE THREAD

**Issue by thesivak** [nette-intellij/intellij-latte#137]
It happens in version 2020.2.4. as well in previous versions.

**Comment by jaroslavlibal** [comment]
A similar thing happens to me - new blank lines are added with each reformatting to some places in code. It seems to happen only in places where a blank line already is. But not always. So far I have not been able to observe the pattern. I suspect it is related to the fact that it is preceded by a condition, but not sure yet :-(

**Comment by mesour** [comment]
Duplicity for: https://github.com/nette-intellij/intellij-latte/issues/115
