### ISSUE TITLE
Missing support for {var $foo += $bar and equivalents

### ISSUE THREAD

**Issue by bohacf** [nette-intellij/intellij-latte#140]
Inspection error: **Tag {var} must contain variable content after =**
```
{var $foo += $bar}
{var $foo .= $bar}
etc.
```

**Comment by mesour** [comment]
@bohacf this is no an error because macro `var` is for variable definition and += or .= is not definition.

You need this for your case:

```
{do $foo += $bar}
{do $foo .= $bar}
```

Or this for Latte < 2.7:

```
{php $foo += $bar}
{php $foo .= $bar}
```
