### ISSUE TITLE
Failed to save settings

### ISSUE THREAD

**Issue by NoxArt** [nette-intellij/intellij-latte#141]
Hi, since PhpStorm 2020.3 whenever I change something (e.g. register a macro) and save, I get a message "Failed to save settings. Please restart PhpStorm", but there is no callstack or more info. After restart macro will not be registered
Version is 1.1.1-RC2, but the same issue was iirc with 1.1.0 and 1.0.2 on this PHPStorm version (I've been trying to solve https://github.com/nette-intellij/intellij-latte/issues/138 so I tried older versions)
Let me know if I should provide more info or try something
Thank you!

**Comment by savalo** [comment]
Same problem with saving custom latte tags in 1.1.1-RC2:

> _Unable to save settings: Failed to save settings. Please restart PhpStorm_

Pstorm is trying to repeat save custom tags repeatedly..

**Comment by mesour** [comment]
Duplicity for https://github.com/nette-intellij/intellij-latte/issues/136
