### ISSUE TITLE
PhpStorm ignores spaces during writing

### ISSUE THREAD

**Issue by david-psondr** [nette-intellij/intellij-latte#142]
Hi,

for example, when I need to write a space character in the command definition - between {} characters, PhpStorm does not display this space. He 's blocking her. I have to get out of the current line and after that move the cursor back.

This only happens while editing latte files.

For exmaple: `{foreach$gamesas$game}`

**Comment by mesour** [comment]
I don't think I fully understand your problem. Can you make a video with your problem? Or write me on Slack.

**Comment by PetrHudik** [comment]
I probably have same issue. When I write latte templates, I just type `{foreach` as normal, than press spacebar and nothing happend. And next letter i press is right after foreach, so result looks like: `{foreach$games`

When i want write something like `{foreach $games as $game}`, I write `{foreach $games`, <SPACE>, <RIGHT KEY>, <LEFT KEY>, and than I can type `$games`. It's realy annoying.

When I disable Latte plugin it works  fine, but whitout Latte plugin :man_shrugging:  I did NOT change any my setting and don't know how to fix it, I tried to change some setting after, but nothing helped. Thanks for any idea.

BTW - what slack workspace?

**Comment by mabar** [comment]
I had the same problem with last release. Can you try install [EAP version](https://github.com/nette-intellij/intellij-latte#testing-eap-versions
)? It fixed problem for me. Or you can just wait for JetBrains approval of just released [1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1) version. 

> BTW - what slack workspace?

Search here for "slack" keyword and invite yourself https://pehapkari.cz

**Comment by hrach** [comment]
I have/had similar problem in html unable to write space after tag name when I wanted continue with class attribute.

**Comment by tulivlk** [comment]
For me it got fixed by adding this repo https://plugins.jetbrains.com/plugins/eap/list to custom repo list and updated plugin to 1.1.1-RC2.

**Comment by PetrHudik** [comment]
> For me it got fixed by adding this repo https://plugins.jetbrains.com/plugins/eap/list to custom repo list and updated plugin to 1.1.1-RC2.

That works for me! thanks!

**Comment by mesour** [comment]
Well, I take it as if it works in 1.1.1-RC2. 1.1.1 stable will soon be approved by JetBrains.
