### ISSUE TITLE
templateType should override default variables

### ISSUE THREAD

**Issue by mabar** [nette-intellij/intellij-latte#146]
e.g. in following case, `$presenter` should be undefined

```php
class TestTemplate
{

}
```

```latte
{templateType TestTemplate}

{$presenter->isLinkCurrent()}
```

**Comment by mesour** [comment]
@mabar you can remove custom variable `presenter` from latte-intellij.xml. Plugin have all variables inside for lower Latte version. If you want change it for specific project. You can change it in settings and latte-intellij.xml
