### ISSUE TITLE
Support for filters and functions defined by templateType class

### ISSUE THREAD

**Issue by mabar** [nette-intellij/intellij-latte#147]
Consider the following example of annotations introduced in https://github.com/nette/latte/releases/tag/v2.7.1 and attributes introduced in https://github.com/nette/latte/releases/tag/v2.10.0:

```php
class TestTemplate
{

	/**
	 * @function
	 */
	#[Latte\Attributes\TemplateFunction]
	public function testingFuntion(): string
	{
		return 'test';
	}

	/**
	 * @filter
	 */
	#[Latte\Attributes\TemplateFilter]
	public function testingFilter(string $test): string
	{
		return strtoupper($test);
	}

}
```

```latte
{templateType TestTemplate}
{var string $test = testingFunction()}

{$test|testingFilter}
```

These features could be implemented:
- function and filter hinting
- parameters and return type resolving
- jump to definition

**Comment by mesour** [comment]
@mabar it is duplicity for https://github.com/nette-intellij/intellij-latte/issues/88
