### ISSUE TITLE
IntelliJ IDEA feezes

### ISSUE THREAD

**Issue by forrest79** [nette-intellij/intellij-latte#148]
I'm using the whole IntelliJ IDEA with PHP plugin (not just PHPStorm) on Windows and last few weeks my IDE often froze (I need to kill idea process and start new one). I had also some other strange behavior in my PHP files - IDE said, that some PHP class does not exist in my project (but it exists). Everything was OK after IDE was restarted. About week ago, I uninstalled latte plugin and everything works OK since then. So I'm suspecting latte plugin. I will be glad to help you figure out, what can go wrong, I just don't know, what can I try or what log is important.

**Comment by hrubostpan** [comment]
I think I have the same problem - stated last week. 
I guess it happens by Copy and paste text in template file (latte-nette framework). When html/php syntax is not correct after paste.

2021-02-23 18:28:41,529 [1741534]  ERROR - guages.TemplateDataElementType - Wrong element created by ASTFactory. See method documentation for details. Here is what we have: elementType: Outer latte; language: Language: Latte; element from factory: PsiElement(Outer latte) 
java.lang.Throwable: Wrong element created by ASTFactory. See method documentation for details. Here is what we have: elementType: Outer latte; language: Language: Latte; element from factory: PsiElement(Outer latte)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)

**Comment by kolinger** [comment]
Same issue here. Started with PhpStorm 2020.3.x and intellijs-latte 1.x.x. Freezes happens randomly when opening latte files. Only with latte files. Doesn't matter on contents. Identical latte file works fine in other project (same version of PhpStorm and intellij-latte). Latte file can be small and simple or huge and complex. Doesn't matter. It seems triggered by errors in latte syntax (when latte is reporting some errors like tag {block} si not closed).

When freeze happens IDE needs to be killed. Sometime restart helps, other times cache invalidation helps, sometimes I need to recreate project. Log files are empty, idea.log doesn't contain anything related. IDE just freezes, doesn't generate any exceptions or warnings before freeze. Can't be reproduced. It's random and dependent on project. But happens every day dependent how often I switch projects. IDE also is generating threadDumps-freeze files until killed - here is example: [threadDump-20210308-141252.txt](https://github.com/nette-intellij/intellij-latte/files/6101664/threadDump-20210308-141252.txt)

Currently using PhpStorm 2020.3.2 (but happened also with 2020.3 and 2020.3.1) and intellij-latte 1.1.2-RC1 (but happened also with 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1).

**Comment by forrest79** [comment]
About a week ago, I installed `1.1.2-RC1` from EAP and since then everything works well. Idea 2020.3.2.

**Comment by mesour** [comment]
Yes, I have same experience as @forrest79 :) Try `1.1.2-RC1` or wait for `1.1.2`. JetBrains is reviewing this update (1-2 bussines days)
