### ISSUE TITLE
Custom macro settings saved in wrong place

### ISSUE THREAD

**Issue by khorsky** [nette-intellij/intellij-latte#149]
I use custom macros, that are marked by plugin as errors. Plugin also offers to add pair/unpaired tag. When I use context action and add selected macro, it works.

What bothers me is an unexpected side effect of this operation - new file "latte.xml" is created in the root of drive, where PHPStorm is installed (D:\latte.xml in my case). Definitely initialized by plugin as could be guessed by file content - `<component name="LattePluginSettings">...`

Tried multiple times.

#136 may be related?

Build:
PhpStorm 2020.3.2
Build #PS-203.7148.74, built on January 27, 2021
Latte plugin 1.1.1

**Comment by mesour** [comment]
@khorsky yes, it is duplicity. Jetbrains probably changed working with settings files, it will be solved in #136
