### ISSUE TITLE
Hint via shortcuts from namespace, not only from class

### ISSUE THREAD

**Issue by mabar** [nette-intellij/intellij-latte#151]
When typing `AdUsEdPr`, phpstorm is able to hint in php code e.g. `App\Admin\User\Edit\Presenter` or `App\AdminUserEditPresenter`. Latte plugin is able to hint only `App\AdminUserEditPresenter` in which all parts of the written string come from classname and not the namespace.

![php](https://user-images.githubusercontent.com/20974277/108085236-669d4700-7075-11eb-86a9-d731929fa4c6.PNG)
![latte](https://user-images.githubusercontent.com/20974277/108085243-68ffa100-7075-11eb-9499-a22e73619963.PNG)

**Comment by mesour** [comment]
Move to https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/129

---

Use Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration
