### ISSUE TITLE
Performance issues when editing file with many comments

### ISSUE THREAD

**Issue by Creeperface01** [nette-intellij/intellij-latte#152]
IntelliJ performance drops significantly when modifying file with many latte comments.

**Comment by mabar** [comment]
Can you please be more specific? `{* latte comments *}` or `<!-- html comments -->`? Do they contain large code blocks or are there just many in the file? Example would be welcome

**Comment by Creeperface01** [comment]
This is the max typing speed I'm getting
latte sample: https://www.dropbox.com/s/1lnza4sibc64646/test.latte?dl=1

https://user-images.githubusercontent.com/10363500/109692182-827e0e00-7b88-11eb-81a9-7ac22ddf9fdd.mp4

**Comment by mesour** [comment]
Maybe duplicity for https://github.com/nette-intellij/intellij-latte/issues/158
