### ISSUE TITLE
create new latte template file from include path if not exists

### ISSUE THREAD

**Issue by chemix** [nette-intellij/intellij-latte#160]
![obrazek](https://user-images.githubusercontent.com/42802/111698525-3a711380-8837-11eb-8130-4aa648e5abb3.png)

**Comment by mesour** [comment]
Moved to Pro plugin: https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/128

---

Use Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration
