### ISSUE TITLE
"Latte configuration reloaded" on every project open

### ISSUE THREAD

**Issue by dakur** [nette-intellij/intellij-latte#161]
**Describe the bug**
When I open a project, it shows this dialog all the time:

![image](https://user-images.githubusercontent.com/9862581/112601124-59ad0980-8e12-11eb-8c1f-a2efa922e45a.png)

I can click `Reparse` and it dismisses with OK, but it is annoying. Can't it be done automatically?

**Environment:**
 - PhpStorm version: 2020.3.3
 - Plugin version: 1.1.2

**To Reproduce**
Steps to reproduce the behavior (or attach video):
1. Open project with Latte files.
2. Click on Reparse.
3. Close it.
4. Open it again.
5. See the dialog again.

I've tried it with clean nette sandbox and it did as well.

**Comment by dakur** [comment]
Actually, it's not "all the time", it's just sometimes. But I can not see relation to anything.

**Comment by peterpp** [comment]
I'm experiencing the same behaviour for a long time. I thought it was related to switching between projects with different PHP version (5.6, 7.3). Now we have all project on PHP 7.3 or 7.4 and it still sometimes happen. But it might be just a coincidence.

**Comment by stpnkcrk** [comment]
It's known behaviour, @mesour explained it here https://youtu.be/ErK0kGQbdNY?t=435 during #posobota s02e03.

**Comment by dakur** [comment]
Thanks. I did not understand it completely, but it is probably something about missing event the plugin can hook onto to trigger reparsing automatically. I'll leave the issue opened until it is resolved or someone decides otherwise.

**Comment by dakur** [comment]
#167 can possibly fix it?

**Comment by mesour** [comment]
@dakur no, I tried it and this cause script loop

**Comment by mesour** [comment]
Resolved in v[1.1.4](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.4)
