### ISSUE TITLE
Problem with load old latte-intellij.xml which cause errors

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#162]
**Describe the bug**
If load old latte-intellij.xml (or some configuration from .idea folder), indexing is freezing.

**Environment (please complete the following information):**
 - PhpStorm version 2020.3
 - Plugin latest

- [ ] As first add some catch to errors and skip errors to continue indexing (and show some error message to user)
- [ ] Try apply some fixes to deprecated/removed functionality from .xml configurations

**Comment by northys** [comment]
This is my `.idea/latte.xml` that caused freezing of PhpStorm when latte opened during initial index. Also, the initial index took forever and did not finish after a hour... Since I've removed this file I had no problems even after enabling all plugins I'm used to work with.

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="LattePluginSettings">
    <option name="variableSettings">
      <list>
        <LatteVariableSettings VarName="control" VarType="\Nette\Application\UI\Control" />
        <LatteVariableSettings VarName="basePath" VarType="string" />
        <LatteVariableSettings VarName="baseUrl" VarType="string" />
        <LatteVariableSettings VarName="baseUri" VarType="string" />
        <LatteVariableSettings VarName="flashes" VarType="mixed[]" />
        <LatteVariableSettings VarName="presenter" VarType="\Nette\Application\UI\Presenter" />
        <LatteVariableSettings VarName="iterator" VarType="\Latte\Runtime\CachingIterator" />
        <LatteVariableSettings VarName="form" VarType="\Nette\Application\UI\Form" />
        <LatteVariableSettings VarName="user" VarType="\Nette\Security\User" />
      </list>
    </option>
    <customMacroSettings>
      <list>
        <LatteTagSettings DeprecatedMessage="" MacroName="_" MacroType="PAIR">
          <option name="vendor" value="OTHER" />
        </LatteTagSettings>
      </list>
    </customMacroSettings>
  </component>
</project>
```

**Comment by mesour** [comment]
XML configuration was removed from free plugin. Use Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro
