### ISSUE TITLE
Argument for @NotNull parameter 'project' of com/jetbrains/php/completion/PhpCompletionUtil.createNamespacePredicate must not be null

### ISSUE THREAD

**Issue by ViPErCZ** [nette-intellij/intellij-latte#173]
**Describe the bug**
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/jetbrains/php/completion/PhpCompletionUtil.createNamespacePredicate must not be null

**Environment (please complete the following information):**
 - PhpStorm version 2021.1.2
 - Plugin version 1.1.2

**To Reproduce**
Steps to reproduce the behavior (or attach video):
always write to latte file

**Screenshots**
![Snímek obrazovky pořízený 2021-05-27 10-28-27](https://user-images.githubusercontent.com/1502711/119792808-4bdd3880-bed6-11eb-8fb5-19c675aa0df8.png)

**Comment by mesour** [comment]
@ViPErCZ try 1.1.3-RC1 - How to install EAP - https://github.com/nette-intellij/intellij-latte#testing-eap-versions

**Comment by mesour** [comment]
1.1.3 is released. In 1-2 business days will be available for download from PhpStorm
