### ISSUE TITLE
Latte not working in Idea 2019.1.4

### ISSUE THREAD

**Issue by faire2** [nette-intellij/intellij-latte#176]
**Describe the bug**
I have installed Latte plugin from the intellij maretplace, but even after restart the syntax is not colored and Code Style settings for Latte are stuck on Loading message. I have tried to uninstall and reinstall the plugin, but the behavior persists - no syntax coloring, settings stuck on Loading

**Environment:**
 - Idea Ultimate  2019.1.4
 - Plugin version 1.0.2

**To Reproduce**
1. Install plugin
2. Open Settings -> Editor -> Code Style -> Latte
3. See error

![image](https://user-images.githubusercontent.com/45813901/128676321-3fb7f955-84e6-41ea-b190-965812e6074a.png)

**Comment by mesour** [comment]
@faire2 hello, thanks for reporting. There were some old versions that had a bug in the settings. It was fixed in later versions. I'm not modifying old versions to support old PhpStorm, but you can make a fork and program it yourself. Otherwise, I recommend updating PhpStorm and also the plugin.
