### ISSUE TITLE
Removing content of <script type="application/json">

### ISSUE THREAD

**Issue by richard-ejem** [nette-intellij/intellij-latte#18]
```
<script type="application/json">
    {$foo}
</script>
```

reports "unexpected end of file" on the second line and is turned into

```
<script type="application/json">

</script>
```

on reformat code.

**Comment by matej21** [comment]
Thanks for the report. But it is probably a bug in phpstorm. Same thing happens in PHP or Smarty files so i'm not sure I can fix it :(

**Comment by fprochazka** [comment]
Is there an issue opened for smarty?

**Comment by matej21** [comment]
I found this php issue: https://youtrack.jetbrains.com/issue/WI-26863 .. since both smarty and latte uses the same feature for HTML code injection it is probably the same bug.

**Comment by mesour** [comment]
Try this in the whole `.html` file. You will get the same syntax error. Because in Latte plugin is used implementation for HTML by JetBrains, than we can not change this behavior.

**Comment by mesour** [comment]
Reformating code in version 1.0.3 will not remove line.
