### ISSUE TITLE
Unexpected {/ifset}, expected {/include}

### ISSUE THREAD

**Issue by DrakMC** [nette-intellij/intellij-latte#191]
**Describe the bug**
The bug is displayed if I use include in ifset.

**Environment (please complete the following information):**
 - PhpStorm version 2021.3
 - Plugin version 1.1.4

**To Reproduce**
1. Use include in ifset.
2. See error

**Code**
https://pastebin.com/raw/xRz1j0ZM

**Screenshots**
- https://i.imgur.com/WLwOT9q.png
- https://i.imgur.com/dYZSwBg.png

**Additional bug**
Additional bug is when I use `{$basePath}` inside block: https://i.imgur.com/4wbLUA4.png
This error will show up: `Unexpected {/block}, expected {/=}`
When I remove `{$basePath}` it works fine.

**Comment by mesour** [comment]
Fixed in v1.1.5
