### ISSUE TITLE
Fatal error with {_} and {/_}

### ISSUE THREAD

**Issue by petrurbanpix** [nette-intellij/intellij-latte#192]
**Describe the bug**
Hi, I have a problem when using the {_} tag with the {/_} ending. When I use it, the plugin throws a fatal error. I leave the log in the link below.

**Environment (please complete the following information):**
 - PhpStorm version 2021.3
 - Plugin version 1.1.4.

**Code**
[error log](https://pastebin.com/N5K9RseX)

**Additional context**
Example:
`{block title}
    {_}hydra_title_admin_tools_accounts{/_}
{/block}`

**Comment by mesour** [comment]
Fixed in v1.1.5
