### ISSUE TITLE
Closing Project dialog is shown for 30+seconds with Latte plugin enabled

### ISSUE THREAD

**Issue by honzavaclavik** [nette-intellij/intellij-latte#202]
**Describe the bug**
When switching projects or closing phpStorm the Closing Project dialog is shown for 30+ seconds and hangs the process

**Environment (please complete the following information):**
 - PhpStorm version 2023.1
 - Plugin version 1.1.7

**To Reproduce**
Steps to reproduce the behavior (or attach video):

1. Open a project
2. Switch to another project using cmd+o and select project - or just quit phpStorm
3. See that the closing dialog shows for a very very long time

**Screenshots**
![image](https://user-images.githubusercontent.com/12621450/230561156-1917ac38-298e-46ad-8a67-1a42d77d79b3.png)

**Additional context**
Disabling the Latte support plugin fixes the problem

**Comment by honzavaclavik** [comment]
Sama problem: https://github.com/nette-intellij/intellij-neon/issues/74

**Comment by badpenguin** [comment]
Same problem here... i hope its not because a "paid" plugin has been introduced.

**Comment by Gappa** [comment]
Haven't encountered this problem so far, so it's not the plugin by itself.

**Comment by rostislavcz** [comment]
Have the same problem. Well the closing is in fact not the problem, but, when you for example open some project and you close it after few seconds, you have to wait about 30 seconds, because this plugin is indexing... Neon plugin is doing the same thing

**Comment by mesour** [comment]
Fixed in 1.1.8 it will be available in 2 business days

**Comment by honzavaclavik** [comment]
Still no realease? 🙏
https://plugins.jetbrains.com/plugin/7457-latte/versions

**Comment by honzavaclavik** [comment]
New release is out and working. Thanks 😉

**Comment by mesour** [comment]
Yes, I probably misclicked somehow when uploading the new version. Or some error on the JetBrains side. Anyway, it's out now :)

**Comment by badpenguin** [comment]
> Yes, I probably misclicked somehow when uploading the new version. Or some error on the JetBrains side. Anyway, it's out now :)

It didn't get applied automatically, you have to manually go to plugin and press update :-(

I hope its not because they are pushing their payed plugin now :-((

**Comment by mesour** [comment]
I have no influence on these updates. This should be handled by PhpStorm itself. I just upload the new version via the web interface.

**Comment by mesour** [comment]
Probably PhpStorm downloads information about new versions only once in a while. So maybe tomorrow or in a few hours it would offer you an update automatically.
