### ISSUE TITLE
%node.word in Structure panel

### ISSUE THREAD

**Issue by SlavaAurim** [nette-intellij/intellij-latte#29]
Thank you so much for the plugin! With it making latte templates very much enjoyable!

Is it possible to show the 1st macro argument ( `[^\s]+` for example ) in the Structure panel?

Now I see in "Structure" this list:

```
block
block
block
block
....

```

But it would be much more useful to see somethig like this: 

```
block head
block TopScreen-logo
block TopScreen-header
block KeyBenefits
....

```

**Comment by mesour** [comment]
@SlavaAurim It is implemented in 1.0.1.
