### ISSUE TITLE
Editing of added macros

### ISSUE THREAD

**Issue by meridius** [nette-intellij/intellij-latte#32]
Can custom added macros be edited/removed somewhere in the IDE?

The reason si when I add custom macro but select its type (paired/unpaired) wrong, I'm stuck with it "forever".

**Comment by matej21** [comment]
There is no configuration dialog, but you can remove it from `.idea/workspace.xml` in your project

**Comment by medhi** [comment]
Can't find my custom macro in `.idea/workspace.xml` in my project folder. Are these stored elsewhere? I thought custom macros are not project based.

**Comment by drml** [comment]
Search for _latte.pair_ or _latte.unpaired_ in `.idea/workspace.xml` file.

**Comment by mesour** [comment]
In 1.0.0 was added UI for settings with more than set custom macros in `Preferences -> Languages & Frameworks -> PHP -> Latte`.

Settings for `latte` is now in `.idea/latte.xml` file.
