### ISSUE TITLE
Macro {translator ... /} is considered as paired

### ISSUE THREAD

**Issue by medhi** [nette-intellij/intellij-latte#36]
`translator ... /}` shows error.

<img width="297" alt="snimek obrazovky 2017-07-17 v 15 28 59" src="https://user-images.githubusercontent.com/522848/28270176-d47e2d2c-6b04-11e7-815f-ba99e00d5535.png">

**Comment by matej21** [comment]
What error does it say?

btw, `translator` is a custom paired macro (which means you can write `{translator ..}{/translator}` or short `{translator ../}`). but I think you've probably added it as a unpaired macro. Please follow #32 and add it again as a pair macro.

**Comment by medhi** [comment]
<img width="1636" alt="snimek obrazovky 2017-07-17 v 17 10 28" src="https://user-images.githubusercontent.com/522848/28274995-decbfc4c-6b12-11e7-9a83-e74a56d511a5.png">

BTW, can't find this custom macro in .idea/workspace.xml in my project folder. Are these stored elsewhere? I thought custom macros are not project based.

**Comment by mesour** [comment]
@medhi Tag translator is not supported: https://latte.nette.org/cs/tags. Use `{_ admin.subdomain}` instead. It can be used as paired without issues `{_}admin.subdomain{/_}`
