### ISSUE TITLE
n:nonce marked as uknown attribute

### ISSUE THREAD

**Issue by soundake** [nette-intellij/intellij-latte#38]
![snimek obrazovky 2018-03-12 v 11 31 47](https://user-images.githubusercontent.com/116968/37278734-f6d74274-25e8-11e8-9015-17f44aa2d201.png)

**Comment by ondrakub** [comment]
@matej21 @JanTvrdik if I prepare PR will you approve it and release new version ?

**Comment by JanTvrdik** [comment]
@soundake You know that you can just hit alt+enter and register the `n:nonce`, right?

**Comment by ondrakub** [comment]
of course, but it is not custom macro, it is official macro from latte, there is no reason why it should not have direct support

**Comment by mesour** [comment]
Resolved in 1.0.0
