### ISSUE TITLE
Calling filters on variables inspection

### ISSUE THREAD

**Issue by ajaxovic** [nette-intellij/intellij-latte#47]
Calling filters on variable is possible from version 2.4
https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc

Plugin still says "Modifiers are not allowed here".
![image](https://user-images.githubusercontent.com/11288002/69427035-ec292e80-0d2e-11ea-9f69-2d40ba546617.png)

**Comment by mesour** [comment]
Implemented in 1.0.2
