### ISSUE TITLE
How to init variables passed from render method?

### ISSUE THREAD

**Issue by Jigsik** [nette-intellij/intellij-latte#52]
Is this plugin somehow looking for variables in render method? If not, how should I define used variables in latte? So far I ended up with this in the beginning of file.

`{varType App\Model\Invoice\Invoice $invoice}`

**Comment by mabar** [comment]
It's in the same thread you linked in #51

**Comment by Jigsik** [comment]
Can I have one more question? Where should I put {templatePrint TestClass} ?
If I put it in any latte I get "Cannot modify header information - headers already sent by".

Thanks

**Comment by mabar** [comment]
No idea, ask at Nette forum

**Comment by Jigsik** [comment]
OK. Thanks.
