### ISSUE TITLE
False positive warning for foreach variable: "Multiple definitions for variable"

### ISSUE THREAD

**Issue by Jigsik** [nette-intellij/intellij-latte#53]
I think internal foreach variables can be "defined" multiple times as a block-scoped variable. Same applies for keys.

![image](https://user-images.githubusercontent.com/10745176/75437693-eeff7500-5956-11ea-939f-4601d5aaae92.png)

**Comment by mesour** [comment]
@Jigsik Multiple definitions for foreach are fixed in 1.0.2. But now I see it like used, but it is unused. I moved it to a new issue: https://github.com/nette-intellij/intellij-latte/issues/54
