### ISSUE TITLE
Macro {label foo} used as unpaired sometimes bugging

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#55]
For example, if used as unpaired and is closed in another macro

**Comment by mesour** [comment]
This will be solved in future with other AUTO_EMPTY macros

**Comment by JanTvrdik** [comment]
Note that auto empty macros are deprecated
https://github.com/nette/latte/commit/442a3ccf073a9df89192202c30fed8380862bb07

**Comment by mesour** [comment]
@JanTvrdik yes, I know, thank you for info :) But David said it is not yet completely figured out how it will be used. As soon as it's clear, I'll work it into the Latte plugin. It will finally solve these problems around AUTO_EMPTY :)
