### ISSUE TITLE
Indentation of newline HTML attributes

### ISSUE THREAD

**Issue by blackhexagon** [nette-intellij/intellij-latte#57]
Firstly, thank you for the plugin, it's a great tool. But I struggle with the indentation of HTML attributes, as it automatically adds 8 spaces before the attributes which are on a newline.

**Before the reformat (desired):**
![image](https://user-images.githubusercontent.com/9962156/76710017-ff0fa680-6703-11ea-9eec-4e2bc30abd87.png)

**After the reformat:**
![image](https://user-images.githubusercontent.com/9962156/76710005-e56e5f00-6703-11ea-8fa1-bac7e1ddf8c7.png)

**Comment by mesour** [comment]
@blackhexagon I hate it too :D But this is not plugin functionality. The plugin only using XML (HTML) formatting from IDE (implementation that is not within our competence). Maybe it can be changed somewhere in code style settings.

You can also find the same behavior in regular .html files.
