### ISSUE TITLE
Not working n:syntax="off"

### ISSUE THREAD

**Issue by ptoseklukas** [nette-intellij/intellij-latte#60]
Hello, 

I use n:syntax="off" parameter and it doesn't work. PHPstorm still inspecting line and, the whole editor is slow. When I click enter i must wait for 2-3 second when new line appears. To the same with typing letters. 

I attach image where n:syntax use. 

![image](https://user-images.githubusercontent.com/37073585/77745899-60951680-701c-11ea-9664-58d7745886a0.png)

Thanks for answer

**Comment by mesour** [comment]
Hi @ptoseklukas, `n:syntax="off"` working for Latte compiler (not for IDE plugin). It is difficult to assess what causes the slowdown. Maybe the solution will be moving this CSS to separated file and for example, load it from file or better is use `<link>` tag to link CSS.

I don't think PHPStorm can turn off checking for some part of the code. As far as I know, it can only do this for the whole file.

It's ok to explain, I'm closing the issue.
