### ISSUE TITLE
Nette\Utils\Html::el() methods are not recognized

### ISSUE THREAD

**Issue by dakur** [nette-intellij/intellij-latte#66]
![image](https://user-images.githubusercontent.com/9862581/79468933-dda22300-7fff-11ea-9102-f23e6d570959.png)

The same for `addAttributes()` and other.

**Comment by mesour** [comment]
@dakur It is because since 2019.2.3 PhpStorm started to prefix _static_ class type with "#S". It will be fixed in `1.0.3` version (next version).

**Comment by dakur** [comment]
Now (1.1.0) it works. Thank you!
