### ISSUE TITLE
Add support for checking required method parameter or parameter types

### ISSUE THREAD

**Issue by dakur** [nette-intellij/intellij-latte#67]
![image](https://user-images.githubusercontent.com/9862581/79540040-c27af600-8087-11ea-8604-ce08cccfe5d8.png)

`LocalDate::now()` has one mandatory parameter, but it is not highlighted like in PHP file.

![image](https://user-images.githubusercontent.com/9862581/79540085-d3c40280-8087-11ea-8410-d04e4f34a953.png)

**Comment by mesour** [comment]
@dakur thanks for your report.

Support for checking required parameters or parameter types is planned for the future.

**Comment by mesour** [comment]
It is fixed in Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration
