### ISSUE TITLE
Inspections for nullable types and intention for optional chaining

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#75]
- [ ] For checking nullable types (eg. calling method on nullable variable)
- [ ] Add intention for add optional chaining (if nullable it will be able to automaticaly insert ? before -> by one click) - nejdříve je třeba implementovat #74

**Comment by adaamz** [comment]
btw how can I write type for nullable variable? Is it possible with {varType} macro or is it possible only via typed templates from nette (php)?

**Comment by mesour** [comment]
Nullable variable is variable with type `null`, `|null` nebo `?string`. Support for `?` is not implemented yes and here is issue: https://github.com/nette-intellij/intellij-latte/issues/83

You can use `{varType string|null $var}` or can mark field on class used in `{templateType ...}` tag. You can too use `{var string|null $var = 123}`.

**Comment by adaamz** [comment]
![image](https://user-images.githubusercontent.com/4347332/84142521-3963b800-aa55-11ea-96a7-14073cce1e69.png)
Seems doesnt work in current stable.

**Comment by mesour** [comment]
Moved to https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/136
