### ISSUE TITLE
Optional chaining - PHP 8 influence: operators ?-> and ??->

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-latte#83]
Latte came up with a optional chaining notation almost a year ago. PHP 8 now comes up with something really very similar and it is named nullsafe operator:

```
$var?->prop?->elem[1]?->call()?->item
```

But the behavior is not exactly the same. Behavior in PHP 8 triggers a warning if a variable, property or array index does not exist (in the given example, if $var, $var->prop or elem[1] does not exist). It just tests if the value is null.

In contrast, the Latte behavior is similar to null coalescing operator ??. Meaning that a non-existent variable, property or array index is not considered as error.

Latte 2.9 unifies the behaviors and the ?-> operator now behaves the same as in PHP to be consistent. But the previous behavior is now implemented by the new undefined-safe operator ??->:

```
$var??->prop??->elem[1]??->call()
```

**Comment by mabar** [comment]
Are you able to use php dependencies in plugin?
https://github.com/phpstan/phpdoc-parser

**Comment by mesour** [comment]
It is fixed in Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration
