### ISSUE TITLE
Invalid content in {var} tag when using concatenation

### ISSUE THREAD

**Issue by adaamz** [nette-intellij/intellij-latte#90]
This code triggers error:
```
{var canWrite = $user->isAllowed($abc.':def', 'read')}
```
as well only this
```
{var canWrite = $abc.':def'}
```

Expected:
No error and optionally correct type of $canWrite var :-)

**Comment by mesour** [comment]
@adaamz It is because in newer Latte you can not use variables without '$'.

I could possibly add a suggestion to change it to a variable, but new plugin changes are mainly for Nette 3+. Deprecated features are not retroactively supported (only some have been in the plugin before).
