### ISSUE TITLE
n:for loop undefined variable

### ISSUE THREAD

**Issue by adaamz** [nette-intellij/intellij-latte#98]
![image](https://user-images.githubusercontent.com/4347332/85027883-b809d500-b17a-11ea-890d-7442b4b988ed.png)
version 1.1.0-rc3

**Comment by mesour** [comment]
It is not working for `for` cycle used as n: attribute (definition as latte tag {for} working correctly).

It will be fixed in future versions.

**Comment by mesour** [comment]
Also fix it for n:tag-for and n:inner-for

**Comment by adaamz** [comment]
Not sure if this should be fixed in 1.1.1-RC2 but my issue still persists.

**Comment by mesour** [comment]
Have you really 1.1.1-RC2? For me, it is working:
![Snímek obrazovky 2020-12-04 v 10 23 59](https://user-images.githubusercontent.com/1161897/101146144-f3119f00-361a-11eb-9c15-d8595c4654ca.png)

**Comment by adaamz** [comment]
I hope yes
![image](https://user-images.githubusercontent.com/4347332/101157485-7edef780-362a-11eb-96f5-6656c220d7a4.png)

**Comment by mesour** [comment]
@adaamz try to reinstall 1.1.1-RC2. It looks like some problem on your side. I have information from other people that this `n:for` works OK.

**Comment by adaamz** [comment]
hm, this is really strange...
I uninstalled plugin -> restarted IDE -> installed plugin again (1.1.1-RC2) -> reloaded configuration -> issue still persists

**Comment by mesour** [comment]
@adaamz try it please in: [v1.1.1](https://github.com/nette-intellij/intellij-latte/releases/tag/v1.1.1)

**Comment by adaamz** [comment]
@mesour still same
![image](https://user-images.githubusercontent.com/4347332/106121195-954f8e00-6157-11eb-83e8-076b120f3881.png)

**Comment by mesour** [comment]
It is fixed in Pro plugin: https://plugins.jetbrains.com/plugin/19661-latte-pro here is migration guide from free plugin: https://mesour-intellij-plugins.github.io/latte.html#migration
